"""marla.messaging.telemetry -- messages.csv raw event log, and the
sent/handled counting rules build_message() and each agent behaviour's
own acceptance point enforce by construction.

See marla.messaging.telemetry's module docstring for the "sent" vs.
"handled" distinction this file exercises: a "sent" event proves a message
was built and addressed; a "handled" event proves the intended MARLA
behaviour actually accepted it for processing. They are recorded at two
different call sites and are never assumed to always both exist.
"""

from __future__ import annotations

import pytest

from marla.messaging import telemetry
from marla.messaging.builders import build_message
from marla.messaging.schemas import MessageMetadata, MessageType


def _metadata(sender="rl_orchestrator", receiver="gatekeeper", message_type=MessageType.READY_CHECK, request_id="req-default"):
    return MessageMetadata(
        performative="request",
        message_type=message_type,
        schema_version="1.0",
        run_id="test-run",
        conversation_id="conv-1",
        request_id=request_id,
        sender_alias=sender,
        receiver_alias=receiver,
    )


@pytest.fixture(autouse=True)
def _reset_telemetry():
    # Never let one test's active log leak into the next.
    telemetry.stop_run()
    yield
    telemetry.stop_run()


def test_build_message_is_a_noop_for_telemetry_when_no_run_is_active():
    build_message("gatekeeper@localhost", _metadata())
    assert telemetry.get_active() is None  # never implicitly started


def test_build_message_records_exactly_one_sent_event_per_call():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata())
    build_message("gatekeeper@localhost", _metadata())
    assert len(log.events) == 2
    assert all(e.event_type == "sent" for e in log.events)


def test_recorded_sent_event_carries_the_full_envelope_and_a_message_id():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(sender="rl_orchestrator", receiver="gatekeeper", request_id="req-1"))
    event = log.events[0]
    assert event.event_type == "sent"
    assert event.sender_alias == "rl_orchestrator"
    assert event.receiver_alias == "gatekeeper"
    assert event.message_type == "READY_CHECK"
    assert event.performative == "request"
    assert event.conversation_id == "conv-1"
    assert event.request_id == "req-1"
    assert event.run_id == "test-run"
    assert event.message_id  # non-empty, generated by build_message()


def test_each_build_message_call_mints_a_distinct_message_id_even_with_identical_envelope_fields():
    """Two CORRECTION_REQUEST retries reuse the same request_id/
    conversation_id/message_type on purpose (spec: retries correlate to the
    same request) -- message_id is what still keeps them distinguishable as
    separate logical messages (invariant E)."""
    log = telemetry.start_run("test-run")
    build_message("plan-maker@localhost", _metadata(message_type=MessageType.CORRECTION_REQUEST, request_id="req-9"))
    build_message("plan-maker@localhost", _metadata(message_type=MessageType.CORRECTION_REQUEST, request_id="req-9"))
    ids = {e.message_id for e in log.events}
    assert len(ids) == 2
    assert log.events[0].request_id == log.events[1].request_id == "req-9"


def test_handled_event_recorded_via_record_handled_if_active():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(sender="rl_orchestrator", receiver="gatekeeper"))
    sent = log.events[0]
    telemetry.record_handled_if_active(
        message_id=sent.message_id, sender_alias=sent.sender_alias, receiver_alias=sent.receiver_alias,
        performative=sent.performative, message_type=sent.message_type,
        conversation_id=sent.conversation_id, request_id=sent.request_id,
    )
    assert len(log.events) == 2
    handled = log.events[1]
    assert handled.event_type == "handled"
    assert handled.message_id == sent.message_id


def test_handled_event_is_a_noop_when_no_run_is_active():
    telemetry.record_handled_if_active(
        message_id="msg-1", sender_alias="rl_orchestrator", receiver_alias="gatekeeper",
        performative="request", message_type="READY_CHECK", conversation_id="conv-1", request_id="req-1",
    )
    assert telemetry.get_active() is None


def test_sent_addressed_and_handled_counts_derive_from_the_same_event_stream():
    """The canonical counting rule: sent-by/addressed-to are two groupings
    of the SENT events, handled-by is a grouping of the HANDLED events --
    all derived from one event list, so they can never drift apart or
    double-count."""
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(sender="rl_orchestrator", receiver="gatekeeper"))
    build_message("plan-maker@localhost", _metadata(sender="rl_orchestrator", receiver="plan_maker_1"))
    sent_3 = build_message("rl-orchestrator@localhost", _metadata(sender="gatekeeper", receiver="rl_orchestrator"))
    event3 = log.events[2]
    telemetry.record_handled_if_active(
        message_id=event3.message_id, sender_alias=event3.sender_alias, receiver_alias=event3.receiver_alias,
        performative=event3.performative, message_type=event3.message_type,
        conversation_id=event3.conversation_id, request_id=event3.request_id,
    )
    del sent_3  # only used to build the message

    summary = log.summarize()
    assert summary["sent_count_by_agent"]["rl_orchestrator"] == 2
    assert summary["sent_count_by_agent"]["gatekeeper"] == 1
    assert summary["addressed_count_by_agent"]["gatekeeper"] == 1
    assert summary["addressed_count_by_agent"]["plan_maker_1"] == 1
    assert summary["addressed_count_by_agent"]["rl_orchestrator"] == 1
    assert summary["handled_count_by_agent"] == {"rl_orchestrator": 1}
    assert summary["total_message_count"] == 3
    assert summary["total_event_count"] == 4  # 3 sent + 1 handled
    assert "received_count_by_agent" not in summary  # deprecated ambiguous name, never retained
    # Every SENT message counted exactly once in aggregate too.
    assert sum(summary["sent_count_by_agent"].values()) == 3
    assert sum(summary["addressed_count_by_agent"].values()) == 3


def test_sent_not_handled_count_makes_an_unmatched_message_visible():
    """A message with no matching behaviour (MARLA has observed real
    "No behaviour matched for message ..." cases) is sent but never
    handled -- this must be a visible discrepancy, not silently absorbed
    into a count that looks the same either way (invariant D)."""
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.START_EXPERIMENT))  # never handled
    handled_msg = build_message("plan-maker@localhost", _metadata(message_type=MessageType.READY_CHECK))
    del handled_msg
    handled_event = log.events[1]
    telemetry.record_handled_if_active(
        message_id=handled_event.message_id, sender_alias=handled_event.sender_alias,
        receiver_alias=handled_event.receiver_alias, performative=handled_event.performative,
        message_type=handled_event.message_type, conversation_id=handled_event.conversation_id,
        request_id=handled_event.request_id,
    )

    summary = log.summarize()
    assert summary["sent_not_handled_count"] == 1


def test_handled_event_never_double_counted_against_sent():
    """Recording a message's sent and handled events must not let either
    inflate the other's total (invariant C)."""
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata())
    sent = log.events[0]
    telemetry.record_handled_if_active(
        message_id=sent.message_id, sender_alias=sent.sender_alias, receiver_alias=sent.receiver_alias,
        performative=sent.performative, message_type=sent.message_type,
        conversation_id=sent.conversation_id, request_id=sent.request_id,
    )
    summary = log.summarize()
    assert summary["total_message_count"] == 1
    assert summary["sent_count_by_agent"]["rl_orchestrator"] == 1
    assert summary["handled_count_by_agent"]["gatekeeper"] == 1
    assert summary["sent_not_handled_count"] == 0


def test_lifecycle_messages_never_carry_decision_context_even_if_context_was_set():
    log = telemetry.start_run("test-run")
    telemetry.set_context(episode_id=5, environment_step=12, global_environment_step=99)
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.STOP_EXPERIMENT))
    event = log.events[0]
    assert event.episode_id is None
    assert event.environment_step is None
    assert event.global_environment_step is None


def test_advisory_messages_carry_decision_context_when_set():
    log = telemetry.start_run("test-run")
    telemetry.set_context(episode_id=3, environment_step=7, global_environment_step=None)
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.ADVISORY_REQUEST, request_id="req-9"))
    event = log.events[0]
    assert event.episode_id == 3
    assert event.environment_step == 7


def test_messages_before_any_set_context_call_have_none_context():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.ADVISORY_REQUEST))
    assert log.events[0].episode_id is None


def test_summary_message_type_and_consultation_counts():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.ADVISORY_REQUEST))
    build_message("rl-orchestrator@localhost", _metadata(sender="gatekeeper", receiver="rl_orchestrator", message_type=MessageType.ADVISORY_RESPONSE))
    build_message("plan-maker@localhost", _metadata(sender="gatekeeper", receiver="plan_maker_1", message_type=MessageType.CORRECTION_REQUEST))
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.READY_CHECK))

    summary = log.summarize()
    assert summary["consultation_request_count"] == 1
    assert summary["consultation_response_count"] == 1
    assert summary["retry_count"] == 1
    assert summary["lifecycle_message_count"] == 1
    assert summary["sent_count_by_type"]["ADVISORY_REQUEST"] == 1
    assert summary["message_count_by_type"]["ADVISORY_REQUEST"] == 1  # kept as an alias of sent_count_by_type


def test_handled_count_by_type_reflects_only_handled_events():
    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.ADVISORY_REQUEST))
    sent = log.events[0]
    telemetry.record_handled_if_active(
        message_id=sent.message_id, sender_alias=sent.sender_alias, receiver_alias=sent.receiver_alias,
        performative=sent.performative, message_type=sent.message_type,
        conversation_id=sent.conversation_id, request_id=sent.request_id,
    )
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.READY_CHECK))  # never handled

    summary = log.summarize()
    assert summary["handled_count_by_type"] == {"ADVISORY_REQUEST": 1}
    assert summary["sent_count_by_type"] == {"ADVISORY_REQUEST": 1, "READY_CHECK": 1}


def test_summarize_empty_log_returns_empty_dict():
    log = telemetry.start_run("test-run")
    assert log.summarize() == {}


def test_stop_run_returns_the_log_and_clears_active():
    telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata())
    log = telemetry.stop_run()
    assert log is not None and len(log.events) == 1
    assert telemetry.get_active() is None
    # further build_message() calls after stop are no-ops for telemetry.
    build_message("gatekeeper@localhost", _metadata())
    assert len(log.events) == 1


def test_write_message_artifacts_writes_csv_and_summary(tmp_path):
    from marla.metrics.writer import write_message_artifacts

    log = telemetry.start_run("test-run")
    build_message("gatekeeper@localhost", _metadata(message_type=MessageType.ADVISORY_REQUEST))
    write_message_artifacts(tmp_path, log)

    assert (tmp_path / "messages.csv").is_file()
    assert (tmp_path / "message_summary.json").is_file()
    import csv

    with (tmp_path / "messages.csv").open() as f:
        rows = list(csv.DictReader(f))
    assert len(rows) == 1
    assert rows[0]["message_type"] == "ADVISORY_REQUEST"
    assert rows[0]["event_type"] == "sent"
    assert rows[0]["message_id"]


def test_write_message_artifacts_is_a_noop_for_none_or_empty_log(tmp_path):
    from marla.metrics.writer import write_message_artifacts

    write_message_artifacts(tmp_path, None)
    assert not (tmp_path / "messages.csv").exists()

    empty_log = telemetry.start_run("test-run")
    write_message_artifacts(tmp_path, empty_log)
    assert not (tmp_path / "messages.csv").exists()


def test_two_sequential_runs_in_the_same_process_do_not_leak_events():
    telemetry.start_run("run-a")
    build_message("gatekeeper@localhost", _metadata())
    log_a = telemetry.stop_run()

    telemetry.start_run("run-b")
    log_b = telemetry.get_active()
    assert log_b.events == []
    build_message("gatekeeper@localhost", _metadata())
    build_message("gatekeeper@localhost", _metadata())
    assert len(log_a.events) == 1  # unaffected by the second run
    assert len(log_b.events) == 2
